In [1]:
import cv2
import numpy as np

In [2]:
mat1 = np.array([[0,0,1,0,0],
                    [0,0,1,0,0],
                    [1,1,1,1,1],
                    [0,0,1,0,0],
                    [0,0,1,0,0]])

mat2 = np.array([[0,0,0,0,0],
                    [0,0,0,0,0],
                    [1,1,1,1,1],
                    [0,0,0,0,0],
                    [0,0,0,0,0]])

mat3 = np.array([[1,0,0,0,1],
                    [0,1,0,1,0],
                    [0,0,1,0,0],
                    [0,1,0,1,0],
                    [1,0,0,0,1]])

mat4 = np.array([[0,0,1,0,0],
                    [0,0,0,0,0],
                    [1,1,1,1,1],
                    [0,0,0,0,0],
                    [0,0,1,0,0]])

In [3]:
def invert_mat(matrix):
    for y in range(matrix.shape[1]):
        for x in range(matrix.shape[0]):
            if matrix[x][y] == 1:
                matrix[x][y]=0
            else:
                 matrix[x][y]=1
    return matrix

In [4]:
add_mat = invert_mat(mat1)
sub_mat = invert_mat(mat2)
mul_mat = invert_mat(mat3)
div_mat = invert_mat(mat4)

In [15]:
kernel1 = np.ones((3,3),dtype='uint8')
kernel= np.array([[1,0,0,0,1],
                   [0,1,1,0,0],
                   [1,1,1,1,1],
                   [0,0,1,1,0],
                   [1,0,1,0,1]])

p = np.array([[1,3,1],
              [2,6,2],
              [1,3,1]])

d = np.array([[4,1,4],
              [1,6,1],
              [4,1,4]])

In [6]:
def convolve(matrix , kernel, padding = 0, stride = 1):
    kernel = np.flipud(np.fliplr(kernel))
    xOut = int(((matrix.shape[0] - kernel.shape[0]+2*padding)/stride)+1)
    yOut = int(((matrix.shape[1] - kernel.shape[1]+2*padding)/stride)+1)
    conv_mat = np.zeros((xOut,yOut))
    
    if padding !=0:
        padded_mat = np.zeros(matrix.shape[0]+padding*2,matrix.shape[1]+2*padding)  
        padded_mat[1:-1,1:-1] = matrix 
    else: padded_mat = matrix
    
    for y in range(matrix.shape[1]):
        if y > matrix.shape[1] - kernel.shape[1]:
            break 
        if y%stride == 0:
            for x in range(matrix.shape[0]):
                if x > matrix.shape[0] - kernel.shape[0]:
                    break
                if x%stride == 0:
                    conv_mat[x,y] = (kernel * padded_mat[x:x+kernel.shape[0],y:y+kernel.shape[1]]).sum()
    return conv_mat

In [7]:
result = convolve(mul_mat,p)
result /= 12
cv2.imshow("MUL", result)
cv2.waitKey(0)
print(result)

[[1.         1.08333333 1.        ]
 [1.         0.83333333 1.        ]
 [1.         1.08333333 1.        ]]


In [29]:
add = convolve(add_mat,p)
add /= 14
cv2.imshow("ADD", add)
cv2.waitKey(0)
print(add)

[[0.5        0.85714286 0.5       ]
 [0.85714286 1.         0.85714286]
 [0.5        0.85714286 0.5       ]]


In [30]:
sub = convolve(sub_mat,p)
sub /= 10
cv2.imshow("SUB", sub)
cv2.waitKey(0)
print(sub)

[[1.4 1.4 1.4]
 [0.8 0.8 0.8]
 [1.4 1.4 1.4]]


In [37]:
div = convolve(div_mat,p)
#div /= 13
cv2.imshow("DIV", div)
cv2.waitKey(0)
print(div)

[[13. 12. 13.]
 [ 8.  8.  8.]
 [13. 12. 13.]]


In [20]:
r2 = convolve(matrix,d)
r2 = r2/24
#r2 = np.array(r2,dtype= 'uint8')
print(r2)

[[0.70833333 0.70833333 0.70833333 0.70833333 0.70833333 0.70833333
  0.70833333 0.5        0.41666667 0.5        0.875      0.75
  0.70833333 0.66666667 0.375      0.66666667 0.54166667 0.875
  0.75       1.         0.5        0.95833333 0.5        0.83333333
  0.70833333 0.54166667 0.66666667 0.54166667]
 [0.75       0.75       0.75       0.79166667 1.         0.79166667
  0.75       0.41666667 0.66666667 0.41666667 0.79166667 1.
  0.79166667 0.75       0.75       0.75       0.75       0.79166667
  1.04166667 0.75       0.95833333 0.16666667 0.95833333 0.70833333
  0.79166667 0.75       0.75       0.75      ]
 [0.70833333 0.70833333 0.70833333 0.875      0.75       0.70833333
  0.66666667 0.33333333 0.41666667 0.5        0.875      0.75
  0.875      0.54166667 0.66666667 0.54166667 0.70833333 0.875
  0.75       1.         0.5        0.95833333 0.5        0.83333333
  0.70833333 0.54166667 0.66666667 0.54166667]]


In [21]:
def threshhold(matrix, val):
    for y in range(matrix.shape[1]):
        for x in range(matrix.shape[0]):
            if matrix[x][y] < val:
                matrix[x][y] = 0
            else:
                matrix[x][y] = 1
    return r2

In [22]:
r2 = threshhold(r2, 0.6)
print(r2)


[[1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1.
  1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1.
  1. 0. 1. 0.]]


In [23]:
cv2.imshow("ConvImg", r2)
cv2.waitKey(0)

113

: 

In [49]:
contours, hierarchies = cv2.findContours(r2, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)} contour(s) found!')

cv2.drawContours(r2, contours, -1, 255, 1)
cv2.imshow('Contours Drawn', r2)

cv2.waitKey(0)

error: OpenCV(4.6.0) D:\bld\libopencv_1657598186226\work\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'


In [92]:
det = np.linalg.det(result)
print(round(det))

0


In [9]:
matrix = np.array([[0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0],
                    [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0],
                    [1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,0,0,1,1,1,1,1],
                    [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0]])

matrix = invert_mat(matrix)

In [10]:
width = 30
height = 5
img = np.ones((height,width))
img[:] = matrix
cv2.imshow("IMAGE",img)
cv2.waitKey()

97

In [ ]:
def mat_detect(img):
    conv_mat = convolve(img,kernel2, stride = 5)
    
    